blueprint:
  name: On at Sunset off later
  description: Turn a light on at Sunset, off at a specified time
  domain: automation
  input:
    target_light:
      name: Light
      description: Light (or Light Group) to be turned on/off
      selector:
        entity:
          domain: light

    off_time:
      name: Time
      description: Time (HH:MM) to turn off Light
      selector:
        time:

trigger:
  - platform: sun
    event: sunset

action:
  - entity_id: !input target_light
    service: light.turn_on

  - wait_for_trigger:
    - platform: time
      at: !input off_time

  - entity_id: !input target_light
    service: light.turn_off

mode: single
