blueprint:
  name: On at Sunset off later
  description: Turn a light on at Sunset, off at a specified time
  domain: automation
  input:
    target_light:
      name: Light
      description: Light (or Light Group) to be turned on/off
      selector:
        entity:
          domain: light
          
    target_brightness:
      name: Brightness
      description: Brightness to set light to (in %, normall 15)
      selector:
        number:
          min: 0
          max: 100
          step: 5
          unit_of_measurement: "%"
          mode: slider
      
    off_time:
      name: Time
      description: Time (HH:MM) to turn off Light
      selector:
        time:

trigger:
  - platform: sun
    event: sunset

action:
  - entity_id: !input target_light
    service: light.turn_on
    data:
      brightness: !input target_brightness

  - wait_for_trigger:
    - platform: time
      at: !input off_time

  - entity_id: !input target_light
    service: light.turn_off

mode: single
