blueprint:
  name: On at Sunset off later
  description: Turn a light on at Sunset, off at a specified time
  domain: automation
  input:
    target_light:
      name: Light
      description: Light (or Light Group) to be turned on/off
      selector:
        entity:
          domain: light
    target_brightness:
      name: Brightness
      description: Brightness to set light to (in %, normall 15)
      selector:
        number:
          min: 0.0
          max: 100.0
          step: 5.0
          unit_of_measurement: '%'
          mode: slider
    off_time:
      name: Time
      description: Time (HH:MM) to turn off Light
      selector:
        time: {}
trigger:
- platform: sun
  event: sunset
- platform: time
  at:
    - !input off_time
action:
  - choose:
    # If we are triggered after sunset but before off_time, turn the light on.
    - conditions:
      - condition: sun
        after: sunset
      - condition: time
        before: !input 'off_time'
      sequence:
        - service: light.turn_on
          data:
            brightness: !input 'target_brightness'
          entity_id: !input 'target_light'

    # If we were triggered after off_time or before sunset turn the light off.
    - conditions:
      - condition: or
        conditions:
          - condition: sun
            before: sunset
          - condition: time
            after: !input 'off_time'
      sequence:
        - service: light.turn_off
          entity_id: !input 'target_light'

    # If we didn't match above, just do nothing
    default:
      - service: system_log.write
        data:
          message: "Automation triggered without reason"
