blueprint:
  name: Reolink Camera Notification
  description: ""
  domain: automation
  
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.reolink_outdoorgarageeast_person
      to: "on"
      for:
        hours: 0
        minutes: 0
        seconds: 0
      id: walk
    - platform: state
      entity_id:
        - binary_sensor.reolink_outdoorgarageeast_vehicle
      to: "on"
      for:
        hours: 0
        minutes: 0
        seconds: 0
      id: car-side
    - platform: state
      entity_id:
        - binary_sensor.reolink_outdoorgarageeast_animal
      to: "on"
      for:
        hours: 0
        minutes: 0
        seconds: 0
      id: rabbit
  condition: []
  action:
    - delay:
        hours: 0
        minutes: 0
        seconds: 3
        milliseconds: 0
      enabled: true
    - action: fetch_latest_file.fetch
      data:
        FileName: Reolink-OutdoorGarageEast
        Directory: /ftproot
    - action: google_generative_ai_conversation.generate_content
      metadata: {}
      data:
        prompt: >-
          What is happening in this picture?  Focus on the subject not the
          surroundings.  If the subject is parked, assume it is actually moving.
          The description needs to be short enough to fit in a phone
          notification. 
        image_filename: "{{ state_attr('fetch_latest_file.file','image') }}"
      response_variable: gemini_response
    - action: notify.melissa_and_scotte_phones
      data:
        message: Reolink Garage East
        data:
          image: https://scotte.ai{{ state_attr('fetch_latest_file.file','image') }}
          notification_icon: mdi:{{ trigger.id }}
          channel: Cameras
          group: Garage East
          visibility: private
          priority: high
          ttl: 0
          sticky: "true"
          subject: "{{ gemini_response['text'] }}"
          clickAction: https://scotte.ai{{ state_attr('fetch_latest_file.file','video') }}
          actions:
            - action: URI
              title: Live
              uri: entityId:camera.reolink_outdoorgarageeast_clear
            - action: URI
              title: Talk
              uri: /dashboard-cameras/garageoutdooreast
    - delay:
        hours: 0
        minutes: 1
        seconds: 0
        milliseconds: 0
  mode: single

