blueprint:
  name: On at Sunset off later
  description: Turn a Switch on at Sunset, off at a specified time
  domain: automation
  input:
    target_switch:
      name: Switch
      description: Switches to be turned on/off
      selector:
        target:
          entity:
            domain: switch
    off_time:
      name: Time
      description: Time (HH:MM) to turn off Switches
      selector:
        time: {}
trigger:
- platform: sun
  event: sunset
- platform: time
  at:
    - !input off_time
action:
  - choose:
    # If we are triggered after sunset but before off_time, turn the switches on.
    - conditions:
      - condition: sun
        after: sunset
      - condition: time
        before: !input 'off_time'
      sequence:
        - service: switch.turn_on
          target: !input 'target_switch'

    # If we were triggered after off_time or before sunset turn the switches off.
    - conditions:
      - condition: or
        conditions:
          - condition: sun
            before: sunset
          - condition: time
            after: !input 'off_time'
      sequence:
        - service: switch.turn_off
          target: !input 'target_switch'

    # If we didn't match above, just do nothing
    default:
      - service: system_log.write
        data:
          message: "Automation triggered without reason"
